#spring.application.name=lakeSide-hotel
#What is YAML (.yml)?                       we use yml to store data not use application.properties
#YAML (Yet Another Markup Language) or
#YAML Ain’t Markup Language is a human-readable data format used for configuration files.
#It is commonly used in applications like Spring Boot
server:
  port: 9192

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

  security:
    user:
      name: admin
      password: admin123

